### ISSUE TITLE
Add to room comment:  room owner name.

### ISSUE THREAD

**Issue by ghost** [team9000/misc#131]
bored reported:

Add the room owner's name to the comment section of the room ID?  Easier to identify who to talk to about issues like whitelist/room name issues.  E.G. Who owns the room blah blah?  Who do need to talk to for whitelist in the room blah blah blah?  Etc.

Mantis project: **web.mumble**
Mantis ID: **133**

**Comment by sonicsnes** [comment]
wontfix, replaced chat with discord
