### ISSUE TITLE
Mumble: Rejoin same lobby

### ISSUE THREAD

**Issue by ghost** [team9000/misc#31]
bored reported:

When users timeout or disconnect they are placed by default in the Lobby channel rather then the room that they disconnected in.  Would prefer to remain in the room that I disconnected from when reconnect.  Probably need an inclusion to move to default if room is deleted by user for the member generated rooms.

Mantis project: **web.mumble**
Mantis ID: **32**

**Comment by sonicsnes** [comment]
wontfix, mumble is dead
