### ISSUE TITLE
Team9000 Launch servers not working!

### ISSUE THREAD

**Issue by ghost** [team9000/misc#532]
flamermw3 reported:

I logged into my account and the server I created for tf2 more than 1 week ago is still just sitting there. Wtf!? This service is getting unreliable.
Please fix this. 
You don't want people to go around hating this service, posting on social media that team9000 is sh1t, don't you? 
Come on!!!!!! Just fix it already.

Mantis project: **web.launch**
Mantis ID: **654**

**Comment by sonicsnes** [comment]
test
